#!/usr/bin/env bash
# Creates an nginx web sever
apt-get update
apt-get install -y nginx

sudo mkdir -p /var/www/html/koeusiss/html

sudo echo "Holberton School" > /var/www/koeusiss/html/index.html

sudo echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name koeusiss.tech www.kouesiss.tech;

    root   /var/www/koeusiss/html;
    index  index.html index.htm;
}" > /etc/nginx/sites-available/koeusiss.tech

sudo rm /etc/nginx/sites-enabled/*
sudo ln -s /etc/nginx/sites-available/koeusiss.tech /etc/nginx/sites-enabled/

sudo service nginx restart
