#!/usr/bin/env bash
# Creates an nginx web sever
apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/koeusiss/html
chown -R "$USER":"$USER" /var/www/koeusiss/html
chmod -R 755 /var/www 
echo "Holberton School" > /etc/nginx/koeusiss/html/index.html
touch /etc/nginx/sites-available/koeusiss.tech
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://example.com/;
    }
}" > /etc/nginx/sites-available/koeusiss.tech
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/example.com /etc/nginx/sites-enabled/

service nginx restart
