#!/usr/bin/env bash
# Fix missing open port 80 in a container
service nginx stop
rm -rf /etc/nginx/sites-enabled/*
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/                                  
