#!/usr/bin/env bash
# Prints "Holberton School" 10 times escaping the 9th

i=1
while [ $i -le 10 ]
do
    if [ $i -ne 9 ]
    then
        echo "Holberton School"
    else
        echo "Hi"
    fi
    (( i++ ))
done
