#!/usr/bin/env bash
# change nginx user
pkill nginx
chown nginx:nginx /etc/nginx/nginx.conf
chmod 600 /etc/nginx/nginx.conf
# sed -i "/^#user.*/c\user nginx;" /etc/nginx/nginx.conf
sudo -u nginx service nginx start
